#!/bin/bash

# kubernetes
alias k='kubectl'
alias m='minikube'
alias tf='terraform'

# enable color for grep
alias grep='grep --color=auto --exclude-dir=node_modules --exclude-dir=vendor'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# enable aliases to be sudo'ed
alias sudo='sudo '

# echo path on separate lines
alias path='echo -e ${PATH//:/\\n}'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

if [ -x /usr/bin/dircolors ]; then
	# shellcheck disable=SC2015
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias dir='dir --color=auto'
	alias vdir='vdir --color=auto'

	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

alias dc='docker'
alias dockerlogin='lpass show --password docker.com | docker login -u jamesnaftel --password-stdin'
alias depgraph='dep status -dot | dot -T png | open -f -a /Applications/Preview.app'

alias glg='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset" --abbrev-commit --date=relative'
alias glt='git log $(git describe --tags --abbrev=0)..HEAD --oneline'
alias gom="export GO111MODULE=on"
alias ybd="cd ~/dev/yourbase"

# aws
alias awsk='aws eks --region us-west-2 update-kubeconfig --name $1'
alias aws='/usr/local/bin/aws'

# heroku
alias ybheroku-staging='heroku psql -a yb-yourbase-api-staging'
alias ybheroku-preview='heroku psql -a yb-yourbase-api-preview'
alias ybheroku-prod='heroku psql -a yb-api'
alias ybheroku-certs='heroku apps | tail -n +2 | xargs -L 1 heroku certs -a'

#yb
alias yb-dev='/Users/jamesnaftel/dev/yourbase/yb/yb'

#nvim
alias v='nvim '
