#!/bin/bash

# kubernetes
alias k='kubectl'
alias m='minikube'
alias tf='terraform'

# enable color for grep
alias grep='grep --color=auto --exclude-dir=node_modules --exclude-dir=vendor'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# enable aliases to be sudo'ed
alias sudo='sudo '

# echo path on separate lines
alias path='echo -e ${PATH//:/\\n}'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

if [ -x /usr/bin/dircolors ]; then
	# shellcheck disable=SC2015
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias dir='dir --color=auto'
	alias vdir='vdir --color=auto'

	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

alias dc='docker'

alias glg='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset" --abbrev-commit --date=relative'
alias glt='git log $(git describe --tags --abbrev=0)..HEAD --oneline'

#fx
alias fxd="cd ~/dev/fx/falcon/"

#nvim
alias v='nvimvenv'
